services:
    php:
        build:
            dockerfile: Dockerfile
            target: php
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:8000
        command: bash -c "php -S 0.0.0.0:8000 -t Src"

    mariadb:
        image: mariadb:11.5.2
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: db_fakeddit
        ports:
            - 3306:3306
        volumes:
            - mariadb:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - mariadb

volumes:
    mariadb: